import { getProductPricing } from "./productPricing.js";

const toFiniteNumber = (value, fallback = 0) => {
  const number = Number(value);
  return Number.isFinite(number) ? number : fallback;
};

const toArray = (value) => {
  if (Array.isArray(value)) return value;
  if (typeof value !== "string" || !value.trim()) return [];

  try {
    const parsed = JSON.parse(value);
    return Array.isArray(parsed) ? parsed : [];
  } catch {
    return [];
  }
};

/**
 * Produces one authoritative pricing view from the order snapshot generated by
 * the API when an order is approved. `discountAmount` and `taxAmount` in that
 * snapshot are per-unit amounts, while `totalPrice` is the complete line total.
 * Before approval there is no discount/tax snapshot, so only the captured order
 * item price is shown; the client never invents an offer or tax.
 */
export const calculateOrderTotals = (order) => {
  const snapshots = toArray(order?.jsonOrderData);
  const items = Array.isArray(order?.items) ? order.items : [];
  const sourceItems = items.length
    ? items
    : snapshots.map((snapshot) => ({
        id: snapshot?.id ?? snapshot?.productId,
        productId: snapshot?.productId,
        product: { id: snapshot?.productId, name: snapshot?.name },
        quantity: snapshot?.quantity,
        price: snapshot?.price,
      }));

  const rows = sourceItems.map((item, index) => {
    const productId = Number(item?.productId ?? item?.product?.id);
    const snapshot = snapshots.find(
      (candidate) => Number(candidate?.productId) === productId,
    );
    const quantity = Math.max(
      toFiniteNumber(snapshot?.quantity ?? item?.quantity, 0),
      0,
    );
    const unitPrice = Math.max(
      toFiniteNumber(snapshot?.price ?? item?.price ?? item?.product?.price, 0),
      0,
    );
    const discountPercentage = Math.max(
      toFiniteNumber(snapshot?.discountPercentage, 0),
      0,
    );
    const unitDiscount = Math.max(
      snapshot && Number.isFinite(Number(snapshot?.discountAmount))
        ? Number(snapshot.discountAmount)
        : unitPrice * discountPercentage / 100,
      0,
    );
    const sellingPrice = Math.max(
      snapshot && Number.isFinite(Number(snapshot?.sellingPrice))
        ? Number(snapshot.sellingPrice)
        : unitPrice - unitDiscount,
      0,
    );
    const taxPercentage = Math.max(
      toFiniteNumber(
        snapshot?.taxPercentage ?? snapshot?.taxpercent,
        0,
      ),
      0,
    );
    const unitTax = Math.max(
      snapshot && Number.isFinite(Number(snapshot?.taxAmount ?? snapshot?.taxamt))
        ? Number(snapshot?.taxAmount ?? snapshot?.taxamt)
        : sellingPrice * taxPercentage / 100,
      0,
    );
    const grossSubtotal = unitPrice * quantity;
    const discountAmount = unitDiscount * quantity;
    const netSubtotal = sellingPrice * quantity;
    const taxAmount = unitTax * quantity;
    const calculatedTotal = netSubtotal + taxAmount;
    const total = Math.max(
      snapshot && Number.isFinite(Number(snapshot?.totalPrice))
        ? Number(snapshot.totalPrice)
        : calculatedTotal,
      0,
    );

    return {
      id: item?.id ?? snapshot?.id ?? `${productId || "product"}-${index}`,
      productId,
      item,
      snapshot,
      name: snapshot?.name || item?.product?.name || item?.name || "Product",
      quantity,
      unitPrice,
      discountPercentage,
      unitDiscount,
      discountAmount,
      sellingPrice,
      grossSubtotal,
      netSubtotal,
      taxPercentage,
      unitTax,
      taxAmount,
      total,
    };
  });

  return {
    rows,
    grossSubtotal: rows.reduce((sum, row) => sum + row.grossSubtotal, 0),
    totalDiscount: rows.reduce((sum, row) => sum + row.discountAmount, 0),
    netSubtotal: rows.reduce((sum, row) => sum + row.netSubtotal, 0),
    totalTax: rows.reduce((sum, row) => sum + row.taxAmount, 0),
    grandTotal: rows.reduce((sum, row) => sum + row.total, 0),
    hasApprovedSnapshot: snapshots.length > 0,
  };
};

export const calculateCartLine = (cartItem) => {
  const quantity = Math.max(toFiniteNumber(cartItem?.quantity, 0), 0);
  const pricing = getProductPricing(cartItem?.product, cartItem?.variation);
  const unitPrice = Math.max(
    toFiniteNumber(pricing.sellingPrice, 0),
    0,
  );

  return {
    quantity,
    unitPrice,
    total: unitPrice * quantity,
  };
};

export const calculateCartTotals = (cartItems = []) => {
  const rows = (Array.isArray(cartItems) ? cartItems : []).map((item) => ({
    item,
    ...calculateCartLine(item),
  }));

  return {
    rows,
    subtotal: rows.reduce((sum, row) => sum + row.total, 0),
  };
};
